# Generated by Django 2.2.1 on 2019-05-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('tarih', models.DateTimeField()),
                ('bitis_saati', models.CharField(max_length=5, verbose_name='bitiş')),
                ('etkinlik_adi', models.CharField(max_length=128, verbose_name='Etkinlik')),
                ('konusmaci_adi', models.CharField(max_length=128, verbose_name='Konuşmacı')),
                ('salon', models.CharField(max_length=30)),
            ],
        ),
    ]
