# Generated by Django 2.2.1 on 2019-05-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etkinlik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='baslangic_saati',
            field=models.CharField(default=10, max_length=5, verbose_name='başlangıç'),
            preserve_default=False,
        ),
    ]
