# Generated by Django 2.2.1 on 2019-05-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etkinlik', '0002_etkinlik_baslangic_saati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='konusmaci_adi',
            field=models.CharField(max_length=128, null=True, verbose_name='Konuşmacı'),
        ),
    ]
