# Generated by Django 2.2.1 on 2019-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etkinlik', '0003_etkinlikmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etkinlikmail',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.AlterField(
            model_name='mail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
