# Generated by Django 2.2.1 on 2019-05-05 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Etkinlik', '0003_auto_20190505_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='konusmaci_adi',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Konuşmacı'),
            preserve_default=False,
        ),
    ]
