# Generated by Django 2.2.1 on 2019-05-03 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Etkinlik', '0004_auto_20190503_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_olusturma',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
